name: My First GitHub Action

on:
  push:
    branches:
      - git-actiin
    workflow_dispatch:

jobs:
  my-first-action:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: list repo files
        run: ls -la

      - name: print a message
        run : echo "deploying to $ENVIRONMENT" 
        env: 
          ENVIRONMENT: staging 