name: My First GitHub Action
on: 
  push:
    branches: [git-action]

jobs:
  my-first-action:
    runs-on: ubuntu-latest
    steps:
      - name: print a message
        run: echo "Hello,world!"